---
- name: update apt system
  apt: update_cache=yes

- name: Install NTP
  apt: name=ntp state=latest update_cache=yes cache_valid_time=3600 force=yes

- name: Set timezone variables
  copy: content='Europe/London'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart NTP
  service: name=ntp state=restarted
