---
- name: Ensure tmp dir exists
  sudo: true
  shell: mkdir -p /tmp/nodejs-install

# See http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/
# and http://nodejs.org/dist
- name: Download Node.js
  sudo: true
  shell: wget https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-armv6l.tar.gz
  args:
    chdir: /tmp/nodejs-install
    creates: /tmp/nodejs-install/node-v4.2.2-linux-armv6l.tar.gz

- name: Extract Node.js
  sudo: true
  shell: tar -xvf node-v4.2.2-linux-armv6l.tar.gz
  args:
    chdir: /tmp/nodejs-install
    creates: /tmp/nodejs-install/node-v4.2.2-linux-armv6l

- name: Copy Node.js
  sudo: true
  shell: sudo cp -R * /usr/local/
  args:
    chdir: /tmp/nodejs-install/node-v4.2.2-linux-armv6l
