---
- name: Clone wiring pi
  sudo: true
  git: repo=git://git.drogon.net/wiringPi dest=/opt/wiringPi accept_hostkey=yes

# see https://projects.drogon.net/raspberry-pi/wiringpi/download-and-install/
- name: Build the wiring pi project
  sudo: true
  shell: ./build
  args:
    chdir: /opt/wiringPi
    # This might not be correct, if there are any errors with the rcswitch for new
    # installation, this is the place to look at!
    creates: /opt/wiringPi/gpio/gpio

- name: Clone rcswitch-pi
  sudo: true
  git: repo=https://github.com/r10r/rcswitch-pi.git dest=/opt/rcswitch-pi/

- name: Build the RCSwitch Pi project
  sudo: true
  shell: make
  args:
    chdir: /opt/rcswitch-pi
    creates: /opt/rcswitch-pi/send

# once installed, the following can be used to send information:
# /opt/rcswitch-pi $ sudo ./send 10111 5 0
#
# Uses the GPIO pin 17 on the raspberry pi
